# Generated by Django 5.2.5 on 2025-08-19 09:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_posts_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posts',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/photos/%Y/%m/%d', verbose_name='Image'),
        ),
    ]
